name: Bygg pull request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.github/workflows/build.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/snyk.yml'
      - '.github/dependabot.yml'
      - '.github/release-drafter.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup maven
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{ "id": "github", "name": "github", "url": "https://maven.pkg.github.com/${{ github.repository }}", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } }]'
          servers: '[{ "id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
          output_file: settings.xml
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: Bygger og tester
        run: mvn install -B -s settings.xml

      - name: Sonar analyse
        if: github.actor != 'dependabot[bot]'
        run: |
          mvn jacoco:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -s settings.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
